### ISSUE TITLE
Cannot Add or Remove any Currencies to Bar

### ISSUE THREAD

**Issue by THusky1** [solocommand/TitanPoints#8] opened 2017-01-18 22:00 UTC
As the title says, this addon used to work for me, but since some recent update (of wow or titan panel, not sure) I can no longer choose which currencies to show, all I see is the expansion headers with no options underneath.

It looks like this: http://www.knightofthelight.co.uk/points.jpg

It still shows the currencies I had configured to show on characters I had used this addon for previously.

**Comment by solocommand** [comment] 2017-01-19 16:09
Hi @THusky1, thanks for the report. I haven't been able to reproduce this, but I'll do some more digging. In the meantime, can you confirm that you do not have the currency headers collapsed on your currency tab?

TitanPoints now loops over this list of currencies so collapsing a header will not display the child currencies (even if you had previously toggled them on in its configuration).

**Comment by THusky1** [comment] 2017-01-20 05:32
If 'headers collapsed' is the problem, the issue is that A) I didnt do
anything to make them collapse (nor do I know how to do this), and B) I
have no way to 'un-collapse' them... they are totally non-interactive.

**Comment by derubm** [comment] 2017-01-24 12:01
![f0hjzfj](https://cloud.githubusercontent.com/assets/6720202/22246715/6963afdc-e236-11e6-8db1-152de3963edd.jpg)

![7in2gri](https://cloud.githubusercontent.com/assets/6720202/22246561/b864ce28-e235-11e6-8495-1139c4f51d2b.jpg)
same here, old characters seem to work, new ones wont. (Legion not collapsable, also the other extensions, only honor kills showed) >> on mouseover it shows all, but not in the bar

**Comment by solocommand** [comment] 2017-01-26 01:46
Hi @THusky1, @derubm.

Sorry for the delay, and thanks for your patience. This issue should now be resolved with the latest release, which was just published. You can update via the Curse Client, or [download the release](https://wow.curseforge.com/projects/titanpanel-points/files/2373247) directly.

This was caused by a change to the TitanPanel library that TitanPoints depends on, which affected the right-click menus for all addons using them in a specific way.

I'm closing this issue as it is now resolved, but please comment back here if you still have trouble after updating, or feel free to open another issue if you run into any other problems.

Thanks!

**Closed as completed by solocommand** 2017-01-26 01:46 UTC

**Comment by THusky1** [comment] 2017-01-26 12:13
I've tested the new release, seems to have fixed the issue.

Semi-related; not sure if this is a new bug but I notice that the legion currencies 'unusual coin' and 'seal of broken fate' are linked, in that toggling display of either one toggles the display of both... the only way to display one without the other is if the one you don't want shown is tagged as unused in the currency tab of the character display, AND the unused category is collapsed.

**Comment by solocommand** [comment] 2017-01-26 15:09
@THusky1 Thanks for the feedback, glad the immediate issue is resolved.

I am aware of the second issue you reported, but at the moment I don't have any plans to fix it soon. Under the hood TitanPoints uses the Blizzard currency icon to determine whether or not a currency should be enabled (specifically this is because the currency icon doesn't change across multiple languages, and certain languages cause errors when trying to save the name of the currency as a SavedVariable).

For whatever reason Blizzard decided that the `Seal of Unusual Fate` and the `Unusual Coin` currencies should use the same icon. So at the moment it can't be changed without breaking support for other languages.

There are a couple other currencies that have the same problem (sorry I can't remember which ones off hand), so it is on my radar to get fixed as soon as I can!

I've created this as an issue on CurseForge for tracking: https://wow.curseforge.com/projects/titanpanel-points/issues/1
